<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TvSite.Domain\TvSite.Domain.csproj" />
      <ProjectReference Include="..\TvSite.Infrastructure\TvSite.Infrastructure.csproj" />
    </ItemGroup>

</Project>
