// <autogenerated />
namespace TvSite.Presentation.Components.Pages
{
    public partial class ProfilePage
    {
        private string DisplayName;

        protected override async Task OnInitializedAsync()
        {
            var authenticationState = await AuthenticationStateProvider.GetAuthenticationStateAsync();
            var user = await UserManager.GetUserAsync(authenticationState.User);

            DisplayName = user?.DisplayName;
        }
    }
}