name: pull_request_and_push_workflow

on:
  pull_request:
    branches:
      - "main"
  push:
  workflow_dispatch: 

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v6
      - run: dotnet restore
      - run: dotnet test
      - run: dotnet build TvSite.Presentation/TvSite.Presentation.csproj
 

  



